#!/usr/bin/env python3
"""
Deploy n8n to Render using the existing database
"""

import os
import subprocess
import sys

def deploy_n8n():
    """Deploy n8n to Render"""
    print("🚀 Deploying n8n to Render...")
    print("=" * 50)
    
    # Check if render.yaml exists
    if not os.path.exists("render-n8n.yaml"):
        print("❌ Error: render-n8n.yaml not found")
        return False
    
    print("✅ Configuration file found")
    print("📋 Database configuration:")
    print("   Host: dpg-d32ft1idbo4c73adbolg-a.oregon-postgres.render.com")
    print("   Database: n8n_database_aumq")
    print("   User: n8n_database_aumq_user")
    print()
    
    print("🌐 Deployment URL will be: https://n8n-workflow-automation.onrender.com")
    print()
    
    print("📝 Next steps:")
    print("1. Go to https://dashboard.render.com")
    print("2. Click 'New +' → 'Blueprint'")
    print("3. Connect your GitHub repository")
    print("4. Select 'render-n8n.yaml' as the blueprint")
    print("5. Click 'Apply' to deploy")
    print()
    
    print("🔑 After deployment, you'll get:")
    print("   - n8n URL: https://n8n-workflow-automation.onrender.com")
    print("   - Admin credentials (generated by Render)")
    print("   - Webhook URL for Flask integration")
    print()
    
    print("⚡ Once deployed, update your Flask app with:")
    print("   N8N_WEBHOOK_URL=https://n8n-workflow-automation.onrender.com")
    print()
    
    return True

if __name__ == "__main__":
    success = deploy_n8n()
    if success:
        print("✅ n8n deployment configuration ready!")
        print("📖 Follow the steps above to deploy to Render")
    else:
        print("❌ Deployment setup failed")
        sys.exit(1)
