[build]
  # Build command for static site generation
  command = "npm install && npm run build"
  
  # Directory to publish
  publish = "dist"
  
  # Functions directory for serverless functions
  functions = "netlify/functions"
  
  # Ignore Python files and backend directory
  ignore = "backend/*"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Set NODE_ENV to production
  NODE_ENV = "production"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy to backend services
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.com/api/:splat"
  status = 200
  force = true

# Environment variables
[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://your-backend-api.com"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  REACT_APP_API_URL = "https://your-backend-api-staging.com"
